---
  - name: tainting as per taint_for_label mapping
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: 'kubectl taint nodes --selector {{ item.label }} {{ item.label }}:{{ item.taint }} --overwrite'
    with_items: "{{ taint_for_label }}"
    tags:
    - taint

